### ISSUE TITLE
Add new lines for each Formatting

### ISSUE THREAD

**Issue by Ph0xEn** [ccancinos/rinzo-xml-editor#15]
Sample Code:
![unbenannt-2](https://f.cloud.github.com/assets/5707600/1350195/e0dc7f2e-3705-11e3-97b5-9624e659ebde.jpg)

First formating:
![unbenannt-3](https://f.cloud.github.com/assets/5707600/1350199/ede98f22-3705-11e3-9da8-377d88901255.jpg)

Second formating:
![unbenannt-4](https://f.cloud.github.com/assets/5707600/1350200/0439fb2c-3706-11e3-9068-b217b39a58bc.jpg)

and so on...
It adds more and more new Lines
Thanks!

Greetings

**Comment by Ph0xEn** [comment]
The Bug still exists in v1.3.0

**Comment by ccancinos** [comment]
Hi Ph0xEn,

I'm having some trouble trying to reproduce this bug on 1.3.0. Not even on eclipse 3.6.2 nor 4.3
Let me tell you what I did:
- I wrote your initial xml using tab as indentation but no luck
- I wrote your initial xml using spaces as indentation but no luck again
- I tried using windows and linux break line as eclipse's configuration with no luck either

![image](https://f.cloud.github.com/assets/5019175/1384444/87787932-3b4d-11e3-9320-bbd8abdf14a4.png)

Am I missing any step or configuration to reproduce this bug?

Thanks
Claudio

**Comment by Ph0xEn** [comment]
Hi ccancinos,

I test some other scenarios and I find out that the bug only work when the String in the Tag is 61 chars long.
If you put 60 chars into the Tag the bug is gone.
But when i add a <![CDATA[ the bug is also gone. 

My Eclipse Version is: 4.3.1

Hope that helps.

Tanks
Philipp
