### ISSUE TITLE
Xml files without schema or dtd definition require a DOCTYPE (dtd definition) on validation

### ISSUE THREAD

**Issue by paulvi** [ccancinos/rinzo-xml-editor#30]
Some XML formats don't have Schema.
There should be way to define exclusion, so that Rinzo does not show error.

Example

http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fp2_composite_repositories.htm

```
<?xml version='1.0' encoding='UTF-8'?>
<?compositeMetadataRepository version='1.0.0'?>
<repository name='"Eclipse Project Test Site"'
    type='org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository'
    version='1.0.0'>
  <properties size='1'>
    <property name='p2.timestamp' value='1243822502499'/>
  </properties>
  <children size='2'>
    <child location='http://example.eclipse.org/childOne'/>
    <child location='http://example.eclipse.org/childTwo'/>
  </children>
</repository>
```

**Comment by ccancinos** [comment]
Hi PaulVi,

What's the error you are having whith this file? I try opening this xml but didn't get any error

Thanks.

**Comment by paulvi** [comment]
![rinzo-error](https://cloud.githubusercontent.com/assets/1614482/3887055/12fff5ec-21ea-11e4-9070-1eeb2f2d2b80.PNG)

It shows that the file has error, and folder and project is in error state, while there should be only light warning inside one file

**Comment by paulvi** [comment]
This is annoying: after I opened `.project` (that does not have schema) with Rinzo-xml my project icon as shown as having error, and Eclipse is warning me every time I launch that the project has errors.

This should be warning level, never affecting build and launch!

**Comment by ccancinos** [comment]
Please add which is the error you are getting on either the Problems or Error Log view in order to analyze this case.

Also you can go to WIndow->Preferences->RInzo XML to change general xml validation severity.

**Comment by paulvi** [comment]
I was just opening .project and .classpath files

After that I was unable to get rid of those errors... yes, I should have check preference

**So what needs to be done is to have suggestion to check preferences when mouse-over those problems.**

A lot of new users will run into the same situation.

**Comment by ccancinos** [comment]
PaulVI, you're still not adding the error message on either the Problems or Error Log view in order to analyze if those errors should not be displayed.

Please do so because I'm still not getting any error using the xml on your description or either .project or .classpath files

**Comment by paulvi** [comment]
I have just installed again.

When opening `.project` I get

```
Multiple markers at this line
    -文档根元素 "projectDescription" 必须匹配 DOCTYPE 根 
     "null"。
    -找不到语法。
```

My OS is Chinese Windows.

In English it is

Multiple markers at this line 
- Document root element "projectDescription" must match DOCTYPE root 
  "null". 
- Can not find the syntax.

When launching project I get

![rinzo-launch](https://cloud.githubusercontent.com/assets/1614482/3995123/2aa9ed48-2923-11e4-97d9-ed15474a80fa.PNG)
