### ISSUE TITLE
Please extend README with how to add more templates

### ISSUE THREAD

**Issue by paulvi** [ccancinos/rinzo-xml-editor#31]
Please extend README with how to add more templates

**Comment by serranoc** [comment]
Our intend is to have an unique documentation. In this case, we prefer explain each Rinzo feature in its website.
Adding Templates are detailed in this section http://editorxml.sourceforge.net/contentAssit.html#Templates  Please let me know if this is what you needed so I can close this issue.

**Comment by paulvi** [comment]
That is exactly. I still propose to add more essential link into README
