### ISSUE TITLE
Tycho build doesn't work

### ISSUE THREAD

**Issue by jvanzyl** [ccancinos/rinzo-xml-editor#36]
I suggest moving the the parent POM to the top of the tree, or create the right references from your child modules.

**Comment by paulvi** [comment]
:+1:

**Comment by paulvi** [comment]
pom.xml from https://github.com/ccancinos/rinzo-xml-editor/tree/master/ar.com.tadp.rinzo.parent should be in the root folder

**Comment by ccancinos** [comment]
What's done in the commit is the choosen way of structurizing Rinzo's projects.
