### ISSUE TITLE
 Syntax Coloring: cannot change color of equal sign

### ISSUE THREAD

**Issue by ccancinos** [ccancinos/rinzo-xml-editor#6]
Using Eclipse Juno SR2 and Rinzo XML editor 1.1.2
There is not option to change the color of the equals sign in the Window->Preferences->Rinzo XML menu.
For example if I make the background black and I have the following code:

``` xml
<module name="Velocity_up" units="m/s">1</module>
```

The equal sign is black and I cannot see it because it blends with the background.
It seems there is no way to change the color of the = sign.

**Comment by serranoc** [comment]
The equal sign color now takes the default text color.
